{"name": "Login_02 : Verify that an error message is displayed when incorrect credentials are entered.", "status": "passed", "attachments": [{"name": "Log", "source": "e5f17064-3a55-4d8a-971d-95bb92c7d22c-attachment.txt", "type": "text/plain"}, {"name": "Log", "source": "b34a70f2-44a7-4d01-a0f7-738a9963be90-attachment.txt", "type": "text/plain"}, {"name": "Log", "source": "88ca5a37-9341-4a13-8091-3508ec7dc362-attachment.txt", "type": "text/plain"}, {"name": "Log", "source": "6c5b93ea-85ff-4cc2-97f7-bda23e9e52a8-attachment.txt", "type": "text/plain"}, {"name": "Popup Assertion Log", "source": "075a602a-bfdf-480d-bc72-6a7b441e91db-attachment.txt", "type": "text/plain"}, {"name": "Popup Text", "source": "cba0d099-9b61-4dd7-a65e-fc128314da9d-attachment.txt", "type": "text/plain"}], "start": 1744093732640, "stop": 1744093737457, "uuid": "3d12a11f-a4fb-4468-a702-38db0d7462c0", "historyId": "ec61bbff0cf4318cf1b0986e358f9e4d", "testCaseId": "ec61bbff0cf4318cf1b0986e358f9e4d", "fullName": "tests.Login.test_Login.TestLogin#test_invalid_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.Login"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PavanKarri"}, {"name": "thread", "value": "88-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Login.test_Login"}]}